#!/bin/bash
# cld container setup: runs once at container creation (postCreateCommand),
# after ToB's post_install.py. Wires GitHub token auth into git and gh.
set -euo pipefail

GITCONFIG_LOCAL="$HOME/.gitconfig.local"

# Break circular include: dotfiles commonly make ~/.gitconfig include
# ~/.gitconfig.local, but in the container GIT_CONFIG_GLOBAL *is*
# .gitconfig.local — the mutual include loops. Disable the include and
# carry the identity over directly.
if ! git config --global user.name >/dev/null 2>&1; then
  sed -i 's|^\[include\]|[cld-disabled-include]|' "$GITCONFIG_LOCAL"
  GIT_NAME=$(git config --file "$HOME/.gitconfig" --no-includes --get user.name 2>/dev/null || true)
  GIT_EMAIL=$(git config --file "$HOME/.gitconfig" --no-includes --get user.email 2>/dev/null || true)
  {
    echo ""
    echo "[user]"
    [ -n "$GIT_NAME" ]  && echo "    name = $GIT_NAME"
    [ -n "$GIT_EMAIL" ] && echo "    email = $GIT_EMAIL"
  } >> "$GITCONFIG_LOCAL"
  echo "[cld-setup] broke circular gitconfig include, carried identity over"
fi

# Git: token auth for github.com over HTTPS, and rewrite SSH remotes to
# HTTPS (host repos use SSH remotes; the sandbox has no SSH keys).
if ! grep -q "cld-credential" "$GITCONFIG_LOCAL" 2>/dev/null; then
  cat >> "$GITCONFIG_LOCAL" <<'EOF'

[credential "https://github.com"]
    helper = !/workspace/.devcontainer/cld-credential.sh
[url "https://github.com/"]
    insteadOf = git@github.com:
[commit]
    gpgsign = false
[tag]
    gpgsign = false
EOF
  echo "[cld-setup] git credential helper configured"
fi

# Docker creates volume mountpoints root-owned; reclaim any under $HOME so
# project-added volumes (caches etc.) are writable without per-project fixes
find "$HOME" -maxdepth 2 -type d -user root 2>/dev/null | while read -r d; do
  sudo chown "$(id -u):$(id -g)" "$d" && echo "[cld-setup] reclaimed $d"
done

# Colima's sshfs mount shows host uid on /workspace while the container
# user is 1000 — git refuses to operate without this (harmless elsewhere)
git config --global --get-all safe.directory 2>/dev/null | grep -qx /workspace || \
  git config --global --add safe.directory /workspace

# gh: wrapper earlier in PATH injects the token freshly on every invocation
# (env vars can't refresh mid-session; a file read can)
REAL_GH=""
for candidate in /usr/bin/gh /usr/local/bin/gh; do
  [ -x "$candidate" ] && REAL_GH="$candidate" && break
done

if [ -n "$REAL_GH" ]; then
  mkdir -p "$HOME/.local/bin"
  cat > "$HOME/.local/bin/gh" <<EOF
#!/bin/sh
if [ -z "\${GH_TOKEN:-}" ] && [ -f "\$HOME/.git-creds/token" ]; then
  GH_TOKEN=\$(cat "\$HOME/.git-creds/token")
  export GH_TOKEN
fi
exec $REAL_GH "\$@"
EOF
  chmod +x "$HOME/.local/bin/gh"
  echo "[cld-setup] gh wrapper installed (wraps $REAL_GH)"
else
  echo "[cld-setup] warning: gh binary not found, skipping wrapper" >&2
fi

# Sandbox operating manual: loaded automatically by Claude Code at session
# start (config-dir CLAUDE.md). Regenerated on rebuild — edit in
# claude-sandbox repo, not here.
#
# Starts with an @import of the host's global CLAUDE.md, which `cld` mounts
# read-only at ~/.git-creds/global-CLAUDE.md and refreshes on every `cld`
# start. Imports resolve at session start, so this stays live across
# restarts even though this file itself is only (re)written at container
# creation.
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
mkdir -p "$CLAUDE_DIR"
if [ ! -f "$CLAUDE_DIR/CLAUDE.md" ] || grep -q "cld-sandbox-manual" "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null; then
  cat > "$CLAUDE_DIR/CLAUDE.md" <<EOF
<!-- cld-sandbox-manual (generated by cld-setup.sh; do not edit here) -->
@$HOME/.git-creds/global-CLAUDE.md

EOF
  cat >> "$CLAUDE_DIR/CLAUDE.md" <<'EOF'
# Sandbox environment

You are running inside a sandboxed devcontainer (cld). The facts below are
about the sandbox itself and are authoritative for this environment — they
override anything conflicting in the imported preferences above. Facts you
must know:

## Persistence
- The container filesystem survives restarts but NOT rebuilds.
- Any environment change that matters (apt packages, `playwright install`,
  tool installs) must ALSO be added to `.devcontainer/devcontainer.json`
  `postCreateCommand` (or the Dockerfile there) and committed, so the
  environment self-heals on rebuild. Do both: install now, persist in config.

## Network
- Internet access is open. Private ranges (10/8, 100.64/10, 172.16/12,
  192.168/16) are deliberately firewalled. "Connection refused/timeout" to
  such addresses is policy, not a bug — do not debug it, do not try to
  disable the firewall.

## GitHub
- `git push` and `gh` already work via a pre-provisioned scoped token.
  NEVER run `gh auth login` or change git credentials.
- The token covers ONLY this repository and rotates hourly (refreshed
  automatically). Access to other repos will fail by design.
- Repo creation/deletion is impossible from here. If needed, ask the human
  to run it on the host.
- Commits are unsigned in the sandbox — expected, do not "fix".
- Before merging a PR, verify CI is green (`gh pr checks`). If CI status is
  not readable or not finished, do NOT merge — report and let the human decide.

## Tooling
- Preinstalled: git, gh, uv (Python 3.13), node 22, build-essential,
  ripgrep, fd, jq. Add project tools via uv/npm; persist per the rule above.
EOF
  echo "[cld-setup] sandbox manual written to $CLAUDE_DIR/CLAUDE.md (imports host global CLAUDE.md via .git-creds)"
fi

echo "[cld-setup] done"
